#!/bin/sh
APP=ansible-container
docker run -it --rm --name $APP -h $APP \
       --cpuset-cpus 0 --memory 2048mb --net host \
       -v ~/Downloads:/home/developer/Downlods \
       -v ~/Documents/Ansible:/home/developer/ansible \
       dmitriiageev/$APP
